### ISSUE TITLE
ERROR: Could not build wheels for dptr, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by zhangchenqi123** [pointrix-project/pointrix#20]
device: RTX 4090
OS: Ubuntu 20.04

When I run `pip install .` , the error appeared
`ERROR: Could not build wheels for dptr, which is required to install pyproject.toml-based projects`

After I installed the `pyproject.toml` through `pip install pyproject.toml`, the error is still there, unchanged.

```
(pointrix) (cuda_12_1 | /code/dptr)
> pip install .
Processing /code/dptr
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in /opt/conda/envs/pointrix/lib/python3.9/site-packages (from dptr==1.0.0) (2.1.1)
Requirement already satisfied: jaxtyping in /opt/conda/envs/pointrix/lib/python3.9/site-packages (from dptr==1.0.0) (0.2.28)
Requirement already satisfied: numpy>=1.20.0 in /opt/conda/envs/pointrix/lib/python3.9/site-packages (from jaxtyping->dptr==1.0.0) (1.26.4)
Requirement already satisfied: typeguard==2.13.3 in /opt/conda/envs/pointrix/lib/python3.9/site-packages (from jaxtyping->dptr==1.0.0) (2.13.3)
Requirement already satisfied: filelock in /opt/conda/envs/pointrix/lib/python3.9/site-packages (from torch->dptr==1.0.0) (3.13.1)
Requirement already satisfied: typing-extensions in /opt/conda/envs/pointrix/lib/python3.9/site-packages (from torch->dptr==1.0.0) (4.9.0)
Requirement already satisfied: sympy in /opt/conda/envs/pointrix/lib/python3.9/site-packages (from torch->dptr==1.0.0) (1.12)
Requirement already satisfied: networkx in /opt/conda/envs/pointrix/lib/python3.9/site-packages (from torch->dptr==1.0.0) (3.1)
Requirement already satisfied: jinja2 in /opt/conda/envs/pointrix/lib/python3.9/site-packages (from torch->dptr==1.0.0) (3.1.3)
Requirement already satisfied: fsspec in /opt/conda/envs/pointrix/lib/python3.9/site-packages (from torch->dptr==1.0.0) (2024.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/envs/pointrix/lib/python3.9/site-packages (from jinja2->torch->dptr==1.0.0) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/envs/pointrix/lib/python3.9/site-packages (from sympy->torch->dptr==1.0.0) (1.3.0)
Building wheels for collected packages: dptr
  Building wheel for dptr (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [92 lines of output]
      /opt/conda/envs/pointrix/lib/python3.9/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at /opt/conda/conda-bld/pytorch_1699449200967/work/c10/cuda/CUDAFunctions.cpp:108.)
        return torch._C._cuda_getDeviceCount() > 0
      No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
      running bdist_wheel
      /opt/conda/envs/pointrix/lib/python3.9/site-packages/torch/utils/cpp_extension.py:502: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/dptr
      copying dptr/__init__.py -> build/lib.linux-x86_64-cpython-39/dptr
      creating build/lib.linux-x86_64-cpython-39/dptr/gs
      copying dptr/gs/ewa_project.py -> build/lib.linux-x86_64-cpython-39/dptr/gs
      copying dptr/gs/compute_cov3d.py -> build/lib.linux-x86_64-cpython-39/dptr/gs
      copying dptr/gs/project_point.py -> build/lib.linux-x86_64-cpython-39/dptr/gs
      copying dptr/gs/__init__.py -> build/lib.linux-x86_64-cpython-39/dptr/gs
      copying dptr/gs/sort_gaussian.py -> build/lib.linux-x86_64-cpython-39/dptr/gs
      copying dptr/gs/compute_sh.py -> build/lib.linux-x86_64-cpython-39/dptr/gs
      copying dptr/gs/alpha_blending.py -> build/lib.linux-x86_64-cpython-39/dptr/gs
      running build_ext
      /opt/conda/envs/pointrix/lib/python3.9/site-packages/torch/utils/cpp_extension.py:424: UserWarning: There are no g++ version bounds defined for CUDA version 12.1
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'dptr.gs._C' extension
      creating build/temp.linux-x86_64-cpython-39
      creating build/temp.linux-x86_64-cpython-39/code
      creating build/temp.linux-x86_64-cpython-39/code/dptr
      creating build/temp.linux-x86_64-cpython-39/code/dptr/dptr
      creating build/temp.linux-x86_64-cpython-39/code/dptr/dptr/gs
      creating build/temp.linux-x86_64-cpython-39/code/dptr/dptr/gs/src
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/code/dptr/setup.py", line 58, in <module>
          setup(
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 91, in run
          _build_ext.run(self)
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 873, in build_extensions
          build_ext.build_extensions(self)
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 252, in build_extension
          _build_ext.build_extension(self, ext)
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py", line 600, in compile
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 609, in unix_wrap_single_compile
          cflags = unix_cuda_flags(cflags)
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 576, in unix_cuda_flags
          cflags + _get_cuda_arch_flags(cflags))
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1967, in _get_cuda_arch_flags
          capability = torch.cuda.get_device_capability(i)
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/torch/cuda/__init__.py", line 435, in get_device_capability
          prop = get_device_properties(device)
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/torch/cuda/__init__.py", line 449, in get_device_properties
          _lazy_init()  # will define _get_device_properties
        File "/opt/conda/envs/pointrix/lib/python3.9/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
          torch._C._cuda_init()
      RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dptr
  Running setup.py clean for dptr
Failed to build dptr
ERROR: Could not build wheels for dptr, which is required to install pyproject.toml-based projects
```

**Comment by yGaoJiany** [comment]
Based on the information you provided, you should firstly install CUDA, which is a must to compile dptr.

**Comment by zhangchenqi123** [comment]
Thanks for your response : )
I was installing the dptr on my new docker container with cuda 12.1 before, but the cuda version of my host machine is 12.0. I think the reason is that mismatch of the cuda version in docker container and my host machine. I test another simple cuda program and it throws an error: `forward compatibility was attempted on non supported HW` in my container.
So I restart another docker container with cuda 11.8 and install the corresponding pytorch-cuda=11.8. Then I reinstall the dptr, and successed.
